### ISSUE TITLE
Please add support for sqlite and sql.js

### ISSUE THREAD

**Issue by MuhAssar** [Seb-C/kiss-orm#3]
To use it in Ionic mobile apps
Thanks

**Comment by ozyman42** [comment]
My first want as well :)
SQLite is also great standalone, and [sql.js](https://github.com/sql-js/sql.js) is just in-browser SQLite.

**Comment by Seb-C** [comment]
Do you know any recommendable package for SQLite that would be cross-platform (NodeJS, ionic, browser...)?

To achieve compatibility with SQLite, one of the difficult things may be the typings. Currently, kiss-orm relies on the fact that the `pg` package returns the proper data types (`string`, `Date`, `number`, `boolean`...). I only have a limited experience with SQLite, but I think the typing is very weak.

The second difficulty I have at the moment is to achieve cross-platform compatibility for the queries in the `CrudRepository`. But I have some ideas to solve this problem already :)

**Comment by ozyman42** [comment]
> Do you know any recommendable package for SQLite that would be cross-platform (NodeJS, ionic, browser...)?

sql.js as I mentioned should be cross-platform since it's just a WASM compilation from the original SQLite C code. The only issue is that the DB is maintained in-memory until exported, so this wouldn't be suitable for large data sets. I wish they would take a filesystem as an input so someone could pass in `fs` for node or alternatively `memfs` or `BrowserFS` for browser. If someone helped to update sql.js to use a supplied instance of fs, would you consider adding sqlite support to kiss-orm?

SQLite is a little unique since it's a file-based DB rather than other DBs where you typically communicate over some transport protocol.

When instantiating a SQLite connector in kiss-orm, kiss-orm could also take an fs instance from the library client.

**Comment by Seb-C** [comment]
So this request is more about `sql.js` than `sqlite` itself.

Even if sql.js is based on sqlite, the fact that it cannot use filesystem databases makes it an inferior and in many cases unusable solution for NodeJS (which is my primary target for this library), especially compared to the `sqlite3` package.

The way I would like to do it then would be to support both, so we would have to classes `SqliteDatabase` for `sqlite3` and `SqlJsDatabase` for `sql.js`.

Honestly it will take quite a lot of time to achieve this compatibility and I don't expect to have time for this any soon unfortunately. The main problems to solve will be:
- How to handle the `sequence` method
- How to (can we) get the proper data types as an output
- How to reliably get the data after an insert (in an implementation-agnostic way like `RETURNING *` does for postgresql)

**Comment by Seb-C** [comment]
I implemented SQLite in v2.0.0 as per the original request (very very soon to be released, more information in #22).
If anyone really needs `sql.js` please open a new issue as the implementation would actually be quite different than SQLite, and I am not willing to spend any more time on it at the moment.

**Comment by Seb-C** [comment]
Please note that the SQLite support will be marked as experimental in v2, as I don't need it myself, so cannot test it as much as I would like except for the existing unit tests.

**Comment by Seb-C** [comment]
v2 has now been published.
